name: suave-jupyter-environment
channels:
  - conda-forge
  - trentonoliphant
  - mlgill
dependencies:
  - python=3.9
  - numpy
  - pip
  - pip:
    - imutils
    - clarifai-grpc
    - spacy
    - tqdm
    - opencv-python-headless
    - opencv-contrib-python-headless
