name: suave-jupyter-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - shapely
  - geopandas
  - panel
  - pysal
  - holoviews
  - hvplot
  - datashader
  - owslib
  - geojson
  - geojsonio
  - psutil
  - matplotlib
  - pandas
  - partd
  - bokeh
  - dask
  - ipywidgets
  - tensorflow
  - scikit-learn
  - keras
  - ipyfilechooser
  - pip:
    - imutils
    - pyvis
