name: suave-jupyter-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - shapely
  - geopandas
  - panel
  - pysal
  - holoviews
  - geojson
  - matplotlib
  - pandas
  - dask
  - ipywidgets
  - tensorflow
  - scikit-learn
  - keras
  - ipyfilechooser
  - pip:
    - imutils
    - pyvis
