name: suave-jupyter-environment
channels:
  - conda-forge
  - trentonoliphant
  - mlgill
dependencies:
  - python
  - numpy
  - pip
  - shapely
  - geopandas
  - panel
  - pysal
  - holoviews
  - hvplot
  - datashader
  - owslib
  - geojson
  - geojsonio
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - pip:
    - imutils
    - clarifai-grpc
    - spacy
    - tqdm
    - opencv-python-headless
    - opencv-contrib-python-headless
    - pandas-profiling
    - pyvis
